# config/_default/menus.en.toml

[[main]]
  name = "About Me"
  pageRef = "about"
  weight = 10
  
[[main]]
  name = "Nutrition Counseling"
  pageRef = "nutrition"
  weight = 30
  
[[main]]
  name = "Sleep Coaching"
  pageRef = "sleep"
  weight = 40

[[main]]
  name = "Resources"
  pageRef = "resources"
  weight = 50
  
[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 60

# [[footer]]
#   name = "Privacy"
#   pageRef = "privacy"
